/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class FrmAroma extends javax.swing.JInternalFrame {

    JDesktopPane pnlPrincipal
            ;

    /**
     * Creates new form FrmCadCliente
     */
    public FrmAroma() {
        initComponents();

    }

    public FrmAroma(JDesktopPane parametro) {
        this();
        pnlPrincipal = parametro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbAroma_Caramelizado = new javax.swing.JComboBox();
        cbAroma_Doce = new javax.swing.JComboBox();
        cbAroma_GraoVerde = new javax.swing.JComboBox();
        jbIncluir_Grao_verde = new javax.swing.JToggleButton();
        jbExcluir_Grao_verde = new javax.swing.JToggleButton();
        jbIncluir_Doce = new javax.swing.JToggleButton();
        jbExcluir_Doce = new javax.swing.JToggleButton();
        jbIncluir_Caramelizado = new javax.swing.JToggleButton();
        jbExcluir_Caramelizado = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        cbAroma_Queimado = new javax.swing.JComboBox();
        cbAroma_Fermentado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbAroma_Amendoa = new javax.swing.JComboBox();
        jbIncluir_Amendoa = new javax.swing.JToggleButton();
        jbExcluir_Amendoa = new javax.swing.JToggleButton();
        jbIncluir_Fermentado = new javax.swing.JToggleButton();
        jbExcluir_Fermentado = new javax.swing.JToggleButton();
        jbIncluir_Queimado = new javax.swing.JToggleButton();
        jbExcluir_Queimado = new javax.swing.JToggleButton();

        setClosable(true);
        setTitle("Cadastro de Aroma");
        setToolTipText("Formulário para a manutenção de dados do cliente.");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Grão verde:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Doce:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Caramelizado:");

        jbIncluir_Grao_verde.setText("Incluir");

        jbExcluir_Grao_verde.setText("Excluir");

        jbIncluir_Doce.setText("Incluir");

        jbExcluir_Doce.setText("Excluir");

        jbIncluir_Caramelizado.setText("Incluir");

        jbExcluir_Caramelizado.setText("Excluir");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Queimado:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Fermentado:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Amêndoa:");

        jbIncluir_Amendoa.setText("Incluir");

        jbExcluir_Amendoa.setText("Excluir");

        jbIncluir_Fermentado.setText("Incluir");

        jbExcluir_Fermentado.setText("Excluir");

        jbIncluir_Queimado.setText("Incluir");

        jbExcluir_Queimado.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbAroma_GraoVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAroma_Doce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAroma_Caramelizado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbIncluir_Caramelizado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir_Caramelizado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbIncluir_Grao_verde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir_Grao_verde))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbIncluir_Doce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir_Doce)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAroma_Amendoa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAroma_Fermentado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAroma_Queimado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbIncluir_Queimado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir_Queimado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbIncluir_Amendoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir_Amendoa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbIncluir_Fermentado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir_Fermentado)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbAroma_Amendoa, cbAroma_Caramelizado, cbAroma_Doce, cbAroma_Fermentado, cbAroma_GraoVerde, cbAroma_Queimado});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbExcluir_Amendoa, jbExcluir_Caramelizado, jbExcluir_Doce, jbExcluir_Fermentado, jbExcluir_Grao_verde, jbExcluir_Queimado, jbIncluir_Amendoa, jbIncluir_Caramelizado, jbIncluir_Doce, jbIncluir_Fermentado, jbIncluir_Grao_verde, jbIncluir_Queimado});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbExcluir_Grao_verde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cbAroma_GraoVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbIncluir_Grao_verde, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbAroma_Doce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbIncluir_Doce)
                            .addComponent(jbExcluir_Doce))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbAroma_Caramelizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbIncluir_Caramelizado)
                            .addComponent(jbExcluir_Caramelizado)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(cbAroma_Amendoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbIncluir_Amendoa)
                                .addComponent(jbExcluir_Amendoa))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(cbAroma_Fermentado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbIncluir_Fermentado))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(cbAroma_Queimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbIncluir_Queimado)
                                .addComponent(jbExcluir_Queimado)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jbExcluir_Fermentado))))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbAroma_Amendoa, cbAroma_Caramelizado, cbAroma_Doce, cbAroma_Fermentado, cbAroma_GraoVerde, cbAroma_Queimado});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbExcluir_Amendoa, jbExcluir_Caramelizado, jbExcluir_Doce, jbExcluir_Fermentado, jbExcluir_Grao_verde, jbExcluir_Queimado, jbIncluir_Amendoa, jbIncluir_Caramelizado, jbIncluir_Doce, jbIncluir_Fermentado, jbIncluir_Grao_verde, jbIncluir_Queimado});

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAroma_Amendoa;
    private javax.swing.JComboBox cbAroma_Caramelizado;
    private javax.swing.JComboBox cbAroma_Doce;
    private javax.swing.JComboBox cbAroma_Fermentado;
    private javax.swing.JComboBox cbAroma_GraoVerde;
    private javax.swing.JComboBox cbAroma_Queimado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jbExcluir_Amendoa;
    private javax.swing.JToggleButton jbExcluir_Caramelizado;
    private javax.swing.JToggleButton jbExcluir_Doce;
    private javax.swing.JToggleButton jbExcluir_Fermentado;
    private javax.swing.JToggleButton jbExcluir_Grao_verde;
    private javax.swing.JToggleButton jbExcluir_Queimado;
    private javax.swing.JToggleButton jbIncluir_Amendoa;
    private javax.swing.JToggleButton jbIncluir_Caramelizado;
    private javax.swing.JToggleButton jbIncluir_Doce;
    private javax.swing.JToggleButton jbIncluir_Fermentado;
    private javax.swing.JToggleButton jbIncluir_Grao_verde;
    private javax.swing.JToggleButton jbIncluir_Queimado;
    // End of variables declaration//GEN-END:variables

    private void limpar() {

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

}