/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidades.Cor;
import entidades.Oleosidade;
import entidades.Turbidez;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import negocio.NCor;
import negocio.NOleosidade;
import negocio.NTurbidez;

/**
 *
 * @author aluno
 */
public class FrmAparencia extends javax.swing.JInternalFrame {

    JDesktopPane pnlPrincipal
            ;

    /**
     * Creates new form FrmCadCliente
     */
    public FrmAparencia() {
        initComponents();
    }

    public FrmAparencia(JDesktopPane parametro) {
        this();
        pnlPrincipal = parametro;
        carregarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel_Aparencia2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbAparencia_Cor = new javax.swing.JComboBox();
        cbAparencia_Oleosidade = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbAparencia_Turbidez = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jbExcluir_Cor = new javax.swing.JToggleButton();
        jbIncluir_Cor = new javax.swing.JToggleButton();
        jbExcluir_Oleosidade = new javax.swing.JToggleButton();
        jbIncluir_Oleosidade = new javax.swing.JToggleButton();
        jbExcluir_Turbidez = new javax.swing.JToggleButton();
        jbIncluir_Turbidez = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Aparência");
        setToolTipText("Formulário para a manutenção de dados do cliente.");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Cor:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Oleosidade:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Turbidez:");

        jbExcluir_Cor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/menos.png"))); // NOI18N
        jbExcluir_Cor.setMaximumSize(new java.awt.Dimension(20, 20));
        jbExcluir_Cor.setMinimumSize(new java.awt.Dimension(20, 20));
        jbExcluir_Cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluir_CorActionPerformed(evt);
            }
        });

        jbIncluir_Cor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/mais.png"))); // NOI18N
        jbIncluir_Cor.setMaximumSize(new java.awt.Dimension(20, 20));
        jbIncluir_Cor.setMinimumSize(new java.awt.Dimension(20, 20));
        jbIncluir_Cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluir_CorActionPerformed(evt);
            }
        });

        jbExcluir_Oleosidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/menos.png"))); // NOI18N
        jbExcluir_Oleosidade.setMaximumSize(new java.awt.Dimension(20, 20));
        jbExcluir_Oleosidade.setMinimumSize(new java.awt.Dimension(20, 20));
        jbExcluir_Oleosidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluir_OleosidadeActionPerformed(evt);
            }
        });

        jbIncluir_Oleosidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/mais.png"))); // NOI18N
        jbIncluir_Oleosidade.setMaximumSize(new java.awt.Dimension(20, 20));
        jbIncluir_Oleosidade.setMinimumSize(new java.awt.Dimension(20, 20));
        jbIncluir_Oleosidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluir_OleosidadeActionPerformed(evt);
            }
        });

        jbExcluir_Turbidez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/menos.png"))); // NOI18N
        jbExcluir_Turbidez.setMaximumSize(new java.awt.Dimension(20, 20));
        jbExcluir_Turbidez.setMinimumSize(new java.awt.Dimension(20, 20));
        jbExcluir_Turbidez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluir_TurbidezActionPerformed(evt);
            }
        });

        jbIncluir_Turbidez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/mais.png"))); // NOI18N
        jbIncluir_Turbidez.setMaximumSize(new java.awt.Dimension(20, 20));
        jbIncluir_Turbidez.setMinimumSize(new java.awt.Dimension(20, 20));
        jbIncluir_Turbidez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluir_TurbidezActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/Aparencia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_Aparencia2Layout = new javax.swing.GroupLayout(jPanel_Aparencia2);
        jPanel_Aparencia2.setLayout(jPanel_Aparencia2Layout);
        jPanel_Aparencia2Layout.setHorizontalGroup(
            jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Aparencia2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Aparencia2Layout.createSequentialGroup()
                        .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Aparencia2Layout.createSequentialGroup()
                                .addComponent(cbAparencia_Turbidez, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbExcluir_Turbidez, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbIncluir_Turbidez, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_Aparencia2Layout.createSequentialGroup()
                                .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbAparencia_Cor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbAparencia_Oleosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_Aparencia2Layout.createSequentialGroup()
                                        .addComponent(jbExcluir_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbIncluir_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_Aparencia2Layout.createSequentialGroup()
                                        .addComponent(jbExcluir_Oleosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbIncluir_Oleosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel1))
                .addGap(50, 50, 50))
        );

        jPanel_Aparencia2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel9});

        jPanel_Aparencia2Layout.setVerticalGroup(
            jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Aparencia2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbAparencia_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbIncluir_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbAparencia_Oleosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbExcluir_Oleosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbIncluir_Oleosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbExcluir_Turbidez, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbIncluir_Turbidez, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Aparencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cbAparencia_Turbidez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel_Aparencia2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Aparencia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Aparencia2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExcluir_CorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluir_CorActionPerformed
         try {
            Cor selecionado = (Cor) cbAparencia_Cor.getSelectedItem();
            new NCor().excluir(selecionado.getId());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbExcluir_CorActionPerformed

    private void jbExcluir_OleosidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluir_OleosidadeActionPerformed
        try {
            Oleosidade selecionado = (Oleosidade) cbAparencia_Oleosidade.getSelectedItem();
            new NOleosidade().excluir(selecionado.getId());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbExcluir_OleosidadeActionPerformed

    private void jbExcluir_TurbidezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluir_TurbidezActionPerformed
        try {
            Turbidez selecionado = (Turbidez) cbAparencia_Turbidez.getSelectedItem();
            new NTurbidez().excluir(selecionado.getId());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbExcluir_TurbidezActionPerformed

    private void jbIncluir_CorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluir_CorActionPerformed
        try {
            Cor cor = new Cor();
            cor.setCor(capturarCor("Cor"));
            new NCor().salvar(cor);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbIncluir_CorActionPerformed

    private void jbIncluir_OleosidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluir_OleosidadeActionPerformed
        try {
            Oleosidade oleosidade = new Oleosidade();
            oleosidade.setQuantidade(capturarPorcentagem("Oleosidade"));
            new NOleosidade().salvar(oleosidade);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbIncluir_OleosidadeActionPerformed

    private void jbIncluir_TurbidezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluir_TurbidezActionPerformed
        try {
            Turbidez turbidez = new Turbidez();
            turbidez.setQuantidade(capturarPorcentagem("Oleosidade"));
            new NTurbidez().Salvar(turbidez);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbIncluir_TurbidezActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAparencia_Cor;
    private javax.swing.JComboBox cbAparencia_Oleosidade;
    private javax.swing.JComboBox cbAparencia_Turbidez;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_Aparencia2;
    private javax.swing.JToggleButton jbExcluir_Cor;
    private javax.swing.JToggleButton jbExcluir_Oleosidade;
    private javax.swing.JToggleButton jbExcluir_Turbidez;
    private javax.swing.JToggleButton jbIncluir_Cor;
    private javax.swing.JToggleButton jbIncluir_Oleosidade;
    private javax.swing.JToggleButton jbIncluir_Turbidez;
    // End of variables declaration//GEN-END:variables

    private void limpar() {

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private void carregarComboBox() {
        try {
            for (Cor obj : new NCor().listar()) {
                cbAparencia_Cor.addItem(obj);
            }
            for (Oleosidade obj : new NOleosidade().listar()) {
                cbAparencia_Oleosidade.addItem(obj);
            }
            for (Turbidez obj : new NTurbidez().listar()) {
                cbAparencia_Turbidez.addItem(obj);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private double capturarPorcentagem(String nomeDoComponente) {
        double porcentagem = -1;
        do {
            try {
                porcentagem = Double.parseDouble(JOptionPane.showInputDialog(null, "Digite a porcentagem", "Cadastrar " + nomeDoComponente, JOptionPane.INFORMATION_MESSAGE));
            } catch (Exception e) {
                continue;
            }
        } while (porcentagem < 1 || porcentagem > 100);
        return porcentagem;
    }

    private String capturarCor(String nomeDoComponente) {
        return JOptionPane.showInputDialog(null, "Digite a cor", "Cadastrar " + nomeDoComponente, JOptionPane.INFORMATION_MESSAGE);
    }

}