/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidades.Cafe;
import entidades.Cafe;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NCafe;

/**
 *
 * @author aluno
 */
public class FrmLisProduto extends javax.swing.JInternalFrame {

    JDesktopPane pnlPrincipal;
    
    public FrmLisProduto() {
        initComponents();
        carregarTabela();
    }

    public FrmLisProduto(JDesktopPane parametro) {
        this();
        pnlPrincipal = parametro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCafe = new javax.swing.JTable();

        setClosable(true);
        setTitle("Lista de café");

        tblCafe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCafeMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCafe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCafeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCafeMousePressed
        try {
            
            int indice = tblCafe.getSelectedRow();
            String id = tblCafe.getValueAt(indice, 0).toString();
            
            Cafe cafe = new NCafe().consultar(
                    Integer.parseInt(id));
            
            FrmCadCafe janela = new FrmCadCafe(
                    pnlPrincipal, cafe);
            pnlPrincipal.add(janela);
            janela.setVisible(true);
            this.dispose();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tblCafeMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCafe;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        try {

            Vector<String> cabecalho = new Vector();
            cabecalho.add("Id");
            cabecalho.add("Nome");
            cabecalho.add("Valor");

            Vector detalhe = new Vector();

            for (Cafe cafe : new NCafe().listar()) {
                Vector<String> linha = new Vector();
                
                linha.add(cafe.getId()+ "");
                linha.add(cafe.getNome());
                linha.add(Double.toString(cafe.getValor()));
                detalhe.add(linha);

            }
            
            tblCafe.setModel(new DefaultTableModel(detalhe,cabecalho));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
}
